### ISSUE TITLE
Modify Raylib Button to use Label instead of fields

### ISSUE THREAD

**Issue by thiagomvas** [thiagomvas/Basalt#15]
Should allow for more consistent text displaying, in case label goes through any changes

**Comment by eae23** [comment]
I'd like to try working on this

**Comment by thiagomvas** [comment]
Alright! Thanks!

If you have any questions feel free to ask them!

By default the cursor is locked on screen but you can remove the ``DisableCursor();`` at line 88 in [RaylibGraphicsEngine.cs](https://github.com/thiagomvas/Basalt/blob/master/Basalt.Raylib/Graphics/RaylibGraphicsEngine.cs) to unlock it.

**Comment by eae23** [comment]
I was just wondering how you test the code you implement

**Comment by thiagomvas** [comment]
Execute the TestField project.

The ``Program.cs`` has a simple scene set up to test on. If you want to test UI components you can just create a new entity with it

```cs
var Something = new Entity();
Something.AddComponent(new Button(Something) { /* Initialize its user-defined fields */});
Engine.CreateEntity(Something);
```

**Comment by eae23** [comment]
I reverted my changes to make sure I could at least render a button before I apply my changes, but there's no button visible.  Do you know what I might be doing wrong?

This is my code in Program.cs:

var testButton = new Entity();
testButton.Id = "entity.testButton";
testButton.Transform.Position = new Vector3(10, 2.5f, 0);
testButton.AddComponent(new Button(testButton) {  Text = "Test Button", TextColor = Color.White, Size = new Vector2(5), BackgroundColor = Color.Red });
Engine.CreateEntity(testButton);

**Comment by thiagomvas** [comment]
Use the ``Offset`` field that ``UIComponent`` has to initialize the position instead of ``Transform.Position``.
You can also change the pivot with the ``Pivot`` field from the same class

The following should work, though haven't tested due to writing this from my phone
```cs
var testButton = new Entity();
testButton.Id = "entity.testButton";
testButton.AddComponent(new Button(testButton) { Text = "Test Button", TextColor = Color.White, Size = new Vector2(5), BackgroundColor = Color.Red, Pivot = UIPivot.MiddleLeft, Offset = new(100, 0) });
Engine.CreateEntity(testButton);
```

**Comment by eae23** [comment]
I think I've done what you were hoping for.  I created a pull request for you to check out and you can let me know if you see any problems or would like for me to make any changes.

**Comment by thiagomvas** [comment]
Looks good to me

I have merged the pull request, thanks for the help!

**Comment by eae23** [comment]
Thank YOU for the opportunity.  This was my first time working on any sort of open source project.

**Comment by thiagomvas** [comment]
No problem!
I often open some simple-ish issues in this repository more as a to-do list whenever i find a bug or need a new feature when using the engine, so if you would like to keep contributing to this project you can keep an eye on it :)
